### ISSUE TITLE
running batch

### ISSUE THREAD

**Issue by mcmasterp** [tomvandeneede/p2pp_s3d#1]
I get this when I first try to run the batch to get the path:

c:\python27\python.exe: can't open file 'E:\Users\Paul\Google': [Errno 2] No such file or directory
Press any key to continue . . .

**Comment by tomvandeneede** [comment]
I have updated the batch file
Most likely you have a space in your filename
I have added quotes to the paramter now, with p2pp in general we always suggest not to use spaces in filenames, but obviously that is not yet documented in p2pp_s3d

l

**Comment by mcmasterp** [comment]
no change. Maybe I'm misunderstanding how to run this initially. It says to run the script witout parameters to get full path to script. So I am double clicking the the batch file in the folder after unzipping . Is this the correct steps?

**Comment by tomvandeneede** [comment]
sent you a pm in facebook

**Comment by tomvandeneede** [comment]
corrected the .bat file to cope with spaces in path and fienames
